kind: pipeline
name: Arch

steps:
- name: Documentation
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C Maintenance upgrade-doxygen
  - make --quiet doxygen

- name: Projects
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make -j --quiet all

- name: Build Tests
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C BuildTests all

# ----

kind: pipeline
name: Ubuntu

steps:
- name: Projects
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make -j --quiet all

- name: Build Tests
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C BuildTests all
