kind: pipeline
name: default

steps:
- name: Documentation
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C Maintenance upgrade-doxygen
  - make --quiet doxygen

- name: Projects
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make -j --quiet all

- name: Bootloaders
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C Maintenance bootloaders

- name: Build Tests
  image: abcminiuser/docker-ci-avr8-toolchain:latest-arch
  commands:
  - make --quiet -C BuildTests all
